platform :ios, '14.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++14'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

      # --- THE MODULAR HEADER FIX ---
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      # ------------------------------

      ['OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |setting|
        config.build_settings[setting] ||= '$(inherited)'
        config.build_settings[setting] << ' -fpermissive -Wno-everything -Wno-error=unused-command-line-argument -Qunused-arguments -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES -Wno-non-modular-include-in-framework-module -Wno-error=non-modular-include-in-framework-module'
      end

      config.build_settings.each do |key, value|
        if value.is_a?(String)
          config.build_settings[key] = value.gsub(/(^|[ \t])-G([ \t]|$)/, ' ')
        end
      end
    end
  end
end